name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: nuget restore JMWPlayer.sln

      - name: Build
        run: msbuild /p:Configuration=Release JMWPlayer.sln

      - name: Publish
        run: msbuild /t:Publish /p:Configuration=Release /p:PublishDir=./output JMWPlayer.sln

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JMWPlayer
          path: ./output

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: JMWPlayer
          path: ./output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./output/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
